/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "NationCraft-Parent"
include(":NationCraft-Bukkit")
include(":NationCraft-Core")
include(":NationCraft-Sponge")
project(":NationCraft-Bukkit").projectDir = file("NationCraft-Bukkit")
project(":NationCraft-Core").projectDir = file("NationCraft-Core")
project(":NationCraft-Sponge").projectDir = file("NationCraft-Sponge")
