name: NationCraft
main: io.github.eirikh1996.nationcraft.NationCraft
version: ${project.version}
author: eirikh1996
commands:
  nation:
    usage: /nation <name>
    description: Creates a new nation
    aliases: [n]
  map:
    usage: /map [auto]
    description: Displays territory map
    #m could have been a viable alias, but that would interfere with Essentials as /m is an alias of /msg
  settlement:
    usage: /settlement <name>
    description: Creates a new settlement
    aliases: [s, sm]
  chatmode:
    usage: /chatmode <chatmode>
    aliases:
      - cm
permissions:
  nationcraft.nation.*:
    default: true
    children:
      create: true
      join: true
      leave: true
      disband: true
      war: true
  nationcraft.settlement.*:
     default: true
     children:
       create: true
  nationcraft.admin.*:
    default: op
