name: NationCraft
main: io.github.eirikh1996.nationcraft.NationCraft
version: 1.0
author: eirikh1996
commands:
  nation:
    usage: /createnation <name>
    description: Creates a new nation
  settlement:
    usage: /createsettlement <name>
    description: Creates a new settlement

