/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    implementation("net.kyori:adventure-text-serializer-plain:4.22.0")
    implementation("net.kyori:adventure-text-serializer-legacy:4.25.0")
    //api(libs.org.jetbrains.annotations)
}

description = "NationCraft-Core"
