/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.19"
    id("com.gradleup.shadow") version "9.0.0-rc2"
}

repositories {
    maven("https://repo.essentialsx.net/releases/")
    maven("https://jitpack.io")
    maven("https://nexus.sirblobman.xyz/public/")
    maven("https://repo.extendedclip.com/releases/")
}

dependencies {
    api(project(":NationCraft-Core"))
    paperweight.paperDevBundle("1.21.10-R0.1-SNAPSHOT")
    compileOnly("net.ess3:EssentialsX:2.18.2")
    compileOnly("com.github.MilkBowl:VaultAPI:1.7.1")
    compileOnly("com.github.sirblobman.api:core:2.9-SNAPSHOT")
    compileOnly("com.github.sirblobman.combatlogx:api:11.4-SNAPSHOT")
    compileOnly("me.clip:placeholderapi:2.11.7")
    //compileOnly(libs.me.clip.placeholderapi)
    compileOnly(files("/../libs/bukkit/VentureChat.jar"))
}

tasks.shadowJar {
    archiveBaseName.set("NationCraft")
    archiveClassifier.set("")
    archiveVersion.set("")
    dependencies {
        include(project(":NationCraft-Core"))
    }
}

description = "NationCraft-Bukkit"
