/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    api("org.yaml:snakeyaml:1.10")
    api("com.google.code.gson:gson:2.8.6")
    api("org.jetbrains:annotations:26.0.2")
    implementation("net.kyori:adventure-api:4.22.0")
    implementation("org.yaml:snakeyaml:2.4")
}

group = "io.github.eirikh1996"
version = "1.0"
java.sourceCompatibility = JavaVersion.VERSION_23
java.targetCompatibility = JavaVersion.VERSION_23

