import org.spongepowered.gradle.plugin.config.PluginLoaders
import org.spongepowered.plugin.metadata.model.PluginDependency

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("org.spongepowered.gradle.plugin") version "2.3.0"
}

repositories {
    maven("https://repo.spongepowered.org/repository/maven-public/")
}

dependencies {
    api(project(":NationCraft-Core"))
    compileOnly("org.spongepowered:spongeapi:17.0.0-SNAPSHOT")
}

sponge {
    apiVersion("17.0.0-SNAPSHOT")
    loader {
        name(PluginLoaders.JAVA_PLAIN)
        version("1.0")
    }
    license("")
    plugin("nationcraft") {
        displayName("NationCraft")
        version("1.0")
        entrypoint("io.github.eirikh1996.nationcraft.sponge.NationCraft")
        description("Just testing things...")
        links {
            homepage("https://github.com/eirikh1996/NationCraft")
            source("https://github.com/eirikh1996/NationCraft")
            issues("https://github.com/eirikh1996/NationCraft/issues")
        }
        contributor("eirikh1996") {
            description("Lead Developer")
        }
        dependency("spongeapi") {
            loadOrder(PluginDependency.LoadOrder.AFTER)
            optional(false)
        }
    }
}

description = "NationCraft-Sponge"
