/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":NationCraft-Core"))
    compileOnly(libs.org.spongepowered.spongeapi)
}

description = "NationCraft-Sponge"
