name: NationCraft
main: io.github.eirikh1996.nationcraft.NationCraft
version: 1.0.0
author: eirikh1996
softdepend:
  - Essentials
  - Vault
commands:
  nation:
    usage: /nation <name>
    description: Creates a new nation
    aliases: [n]
  nationcraft:
    description: NationCraft main command
    aliases: [nc]
  map:
    usage: /map [auto]
    description: Displays territory map
    #m could have been a viable alias, but that would interfere with Essentials as /m is an alias of /msg
  settlement:
    usage: /settlement <name>
    description: Creates a new settlement
    aliases: [s, sm]
  chatmode:
    usage: /chatmode <chatmode>
    aliases:
      - cm

  player:
    usage: /player
    aliases:
      - p
permissions:
  nationcraft.nation.*:
    default: op
    children:

  nationcraft.settlement.*:
     default: true
     children:
       create: false
  nationcraft.admin:
    default: op
  nationcraft.nation.create:
    default: true
  nationcraft.nation.join:
    default: true
  nationcraft.nation.leave:
    default: true
  nationcraft.nation.disband:
    default: true
  nationcraft.nation.claim:
    default: true
  nationcraft.nation.war:
    default: true